# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Blog
tagline:             'A Blog.'
description:         'A Blog.'
url:                 http://benignbemine.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Kyle Owen
  email:             kyle.17.owen@gmail.com

